name: Tests
on:
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: install dependencies
      run: sudo apt install gcc-aarch64-linux-gnu qemu-user
    - name: Run Dilithium NTT Tests
      run: |
        make run-cross-ntt_dilithium
    - name: Run Kyber NTT Tests
      run: |
        make run-cross-ntt_kyber
    - name: Run Kyber NTT Tests
      run: |
        make run-cross-ntt_kyber
    - name: Run X25519 Tests
      run: |
        make run-cross-x25519
    - name: Run Keccak Tests
      run: |
        make clean
        make run-cross-keccak_neon